In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))

In [2]:
from src.transforms import trainval_transforms, revert_normalization, revert_standardization
from src.dataset import ImageDataset
import torch

annot_path = Path("../data/preprocessed/trainval/annotations.csv")
img_dir = Path("../data/preprocessed/trainval/images")

# test dataset without transforms
dataset = ImageDataset(annot_path, img_dir, transform=trainval_transforms)

In [3]:
from src.model import Model
from torch.utils.data import DataLoader

trainval_dl = DataLoader(dataset, 8, True)
X_batch, y_batch = next(iter(trainval_dl))
model = Model()

model.eval()
with torch.no_grad():
    preds_batch = model(X_batch)
    
preds_batch.shape, preds_batch

(torch.Size([8, 7, 7, 25]),
 tensor([[[[-3.7564e-04, -8.2305e-03,  1.0993e-03,  ..., -6.8040e-03,
            -5.4670e-03,  6.5597e-03],
           [-1.0394e-02, -1.3126e-02,  1.2908e-03,  ...,  1.0362e-02,
            -8.5069e-03, -1.1125e-02],
           [ 1.0307e-02, -6.9847e-03, -2.2317e-02,  ..., -3.5650e-03,
             1.1577e-04, -8.0210e-03],
           ...,
           [-1.4035e-02,  1.3577e-03,  9.5510e-03,  ...,  3.3276e-03,
             3.0393e-03,  1.1855e-02],
           [ 5.4855e-03,  7.6513e-03,  2.0788e-02,  ...,  2.1667e-03,
             1.3867e-02,  3.2472e-03],
           [ 1.3994e-02,  1.4573e-03,  8.9919e-03,  ...,  8.8432e-04,
            -3.2092e-04,  1.8767e-02]],
 
          [[-1.0503e-02, -1.9316e-02, -3.5792e-03,  ..., -1.2312e-03,
             2.5414e-04, -9.1961e-04],
           [-1.3443e-02,  4.5155e-03,  6.7564e-03,  ...,  8.7748e-03,
             5.5820e-03, -1.3254e-02],
           [ 5.6711e-03, -2.6378e-03, -5.9523e-03,  ...,  8.7739e-03,
           

In [4]:
from src.postprocessing import decode_preds_batch

decoded_preds_batch = decode_preds_batch(preds_batch)
decoded_preds_batch[0]

tensor([[ 9.0000e+00,  1.0329e-04,  9.9422e-01,  6.8855e-01, -5.2986e-01,
         -5.3606e-01],
        [ 1.8000e+01, -2.8581e-04,  3.0246e+01,  4.7519e-01,  3.2567e+01,
         -1.4304e+00],
        [ 8.0000e+00, -1.3863e-04,  6.4851e+01, -2.8736e-01,  6.4053e+01,
         -2.6143e-01],
        [ 6.0000e+00, -3.0455e-04,  9.5004e+01, -5.9401e-01,  9.7599e+01,
          8.5351e-01],
        [ 8.0000e+00,  2.1807e-04,  1.2764e+02, -3.8969e-02,  1.2839e+02,
          6.4184e-01],
        [ 2.0000e+00,  6.7503e-05,  1.5966e+02, -1.5135e+00,  1.6015e+02,
          1.5929e+00],
        [ 1.3000e+01,  3.3915e-04,  1.9162e+02,  8.7823e-02,  1.9181e+02,
          1.5937e-02],
        [ 1.0000e+01, -1.3659e-05, -4.6580e-01,  3.1794e+01, -7.4160e-01,
          3.1851e+01],
        [ 1.5000e+01, -1.9691e-04,  3.0311e+01,  3.0876e+01,  3.2277e+01,
          3.2126e+01],
        [ 1.3000e+01, -4.1724e-06,  6.3586e+01,  3.2392e+01,  6.5551e+01,
          3.1565e+01],
        [ 1.5000e+01, -5.7712e

In [5]:
from src.postprocessing import filter_and_group_preds

filtered_and_grouped_preds = filter_and_group_preds(decoded_preds_batch[0])
filtered_and_grouped_preds

tensor([ 9.0000e+00,  1.0329e-04,  9.9422e-01,  6.8855e-01, -5.2986e-01,
        -5.3606e-01])


KeyError: tensor(9.)